server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  security:
    oauth2:
      client:
        registration:
          products-client-oidc:
            provider: spring
            client-id: products-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8081/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: products-client-oidc
          products-client-authorization-code:
            provider: spring
            client-id: products-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8081/authorized"
            scope: products.read
            client-name: products-client-authorization-code
        provider:
          spring:
            issuer-uri: http://localhost:9000